# Generated by Django 4.0.1 on 2022-01-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
