# Generated by Django 4.0.1 on 2022-01-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
